### ISSUE TITLE
Maximal theoretical memory bandwidth

### ISSUE THREAD

**Issue by gmtime** [intel/intel-cmt-cat#109]
With pqos, is there a way to get/calculate maximal theoretical memory bandwidth per system/ core/rmid ? The idea is to be able to see how close we are to the theoretical limits.

**Comment by anastop** [comment]
I would bet that the best way to measure the memory b/w would be to use benchmarks, e.g. STREAM (https://github.com/jeffhammond/STREAM) has been the de-facto benchmark for years. I know that you can use it on a system-wide basis, so playing around with task affinity options could help you do the same on a per-core or per-socket basis.

**Comment by mdcornu** [comment]
Calculating the max memory bandwidth is difficult since it depends on many factors such as CPU frequencies, memory configuration, memory operation types etc. I agree that the best way to measure this is to run a benchmark to stress the bandwidth. Stream is a good option. Another potential option is MLC (memory latency checker) which has an option to stress local memory bandwidth (mlc --max_bandwidth) with different read-write ratios.

Regards,
Marcel

**Comment by anastop** [comment]
@mdcornu , is mlc open source?

**Comment by tkanteck** [comment]
It is not available under any usual open source license and its source code is not  available.
It is distributed and binary but its license gives reasonable level of freedom of use:


> 1) internally reproduce and install a reasonable number of copies of the Materials for Your internal use solely for the purposes of designing, developing, manufacturing and testing Intel-based Devices;

See more here:
https://software.intel.com/en-us/articles/intelr-memory-latency-checker

**Comment by kmabbasi** [comment]
going to close it now. 
feel free to create new issue if you have more concerns.
