### ISSUE TITLE
pqos -I invalid option

### ISSUE THREAD

**Issue by diksha11s** [intel/intel-cmt-cat#113]
![invalid](https://user-images.githubusercontent.com/51041344/61680695-9b4dee80-acd8-11e9-86b1-6a860a2b5585.jpg)
![config](https://user-images.githubusercontent.com/51041344/61680728-b91b5380-acd8-11e9-8d61-e4dd514f18be.JPG)

**Comment by kmabbasi** [comment]
It looks like you are using very old version of pqos which doesn't support -I option. Which Linux kernel version are you using?

Could you clone and try this one https://github.com/intel/intel-cmt-cat

Thanks,
Khawar

**Comment by diksha11s** [comment]
Version: Linux 4.15.0-51-generic x86_64
![command](https://user-images.githubusercontent.com/51041344/61755643-86c82f80-ad86-11e9-86ba-1ba372b04494.jpg)
I tried this as well after cloning.

**Comment by mdcornu** [comment]
Looks like you are using an uppercase L when setting the path to the lib directory.
It should be ./lib instead of ./Lib

Another option is to install the library and tools with `sudo make install`.
If using a RedHat based distro such as Fedora, you may also have to do one more step outlined [here](https://github.com/intel/intel-cmt-cat/wiki/FAQ#when-i-try-to-run-the-utility-i-get-the-following-error-message).

Regards,
Marcel

**Comment by diksha11s** [comment]
Thank you so much!! It's working :)
