### ISSUE TITLE
PCM and Linux resctrl Compatibility

### ISSUE THREAD

**Issue by mRSun15** [intel/intel-cmt-cat#160]
In the Software Compatibility part, the table told that Linux resctrl and PCM cannot work together. Could you please explain why they are not compatible? In my program, I use the PCM to read the DDR latency and resctrl to monitor the Memory Bandwidth data, but I get both data successfully? Is the data not accurate? 

Thanks!!

**Comment by mdcornu** [comment]
The resctrl kernel framework is not aware of user space tools who are also monitoring RDT events. By default, the pcm-memory.x utility will start to monitor per core memory bandwidth using RDT. If resctrl is being used to monitor in parallel, this can lead to invalid data being reported as both tools are potentially overwriting the same MSR's used to monitor. 

A recent [commit](https://github.com/opcm/pcm/commit/0e7e0e9f2f0b21566965781115e8ca7b08fcaede#diff-d1c5af0d846a6f7d4f880d71dbd8b178) to PCM has provided an option (environment variable) to disable RDT monitoring in pcm-memory.x.

Usage:
sudo PCM_NO_RDT=1 ./pcm-memory.x

Regards,
Marcel

**Comment by mRSun15** [comment]
Hi Marcel, 

Thanks for the reply. To verify your answer, I did some experiments. First, I wrote a program which will consecutively read memory periodically, then, I did two experiments: one was just using RDT to monitor the Memory-Read data, another one was running the pcm-memory.x and RDT together to get the Memory-Read data. To my surprise, I found that there are no obvious difference between these two data. It seems that PCM didn't influence RDT's work, which is contradictory with what you said before. 

Hence, I doubted that as you said "both tools are potentially ovewriting the same MSR", what "potentially" here means? when it will overwrite the data? And if this happens, what impact it will have on RDT's monitor data? Also, I was confused that RDT Memory monitor will use OS kernel rather than MSR to monitor the memory data, right? If so, why the conflicts exist here?

Sorry, I have too many questions. 

Thanks again!

**Comment by mdcornu** [comment]
Sorry for the delay, I somehow missed your response so apologies for that.

When I say "potentially overwriting the same MSR's" I mean that there is a chance both tools could program different RMID values to the same core which will invalidate the data reported by the tool who's RMID value was overwritten.

The intel-cmt-cat tools support programming RDT using MSR's and the OS.
By default, the MSR interface is used. To use the OS interface, add the `-I `option when using the applications.
e.g. To monitor cores 0-5 with OS interface: `pqos -I -m all:0-5`

Regarding your experiment, the pcm-memory.x tool output shows memory reported per socket which is read from different counters, so you won't see any difference there. However, pcm-memory.x is re-programming new RMID values to the RDT MSR's which will affect the output reported by the pqos utility.

A simple experiment to check if PCM is programming the MSR's:
1. Reset RDT allocation and monitoring: `pqos -rR`
2. Check core RMID association: `pqos -s`
Should see all RMID0 e.g.:
```
Core information for socket 0:
    Core 0, L2ID 0, L3ID 0 => COS0, RMID0
    Core 1, L2ID 1, L3ID 0 => COS0, RMID0
    Core 2, L2ID 2, L3ID 0 => COS0, RMID0
    Core 3, L2ID 3, L3ID 0 => COS0, RMID0
```
3. Start PCM: `pcm-memory.x` (in a different terminal)
4. Re-check core RMID association: `pqos -s`
```
Core information for socket 0:
    Core 0, L2ID 0, L3ID 0 => COS0, RMID111
    Core 1, L2ID 1, L3ID 0 => COS0, RMID110
    Core 2, L2ID 2, L3ID 0 => COS0, RMID109
    Core 3, L2ID 3, L3ID 0 => COS0, RMID108
```
Cores have been associated to new RMID values.
If RMID0 is still being used, then PCM is not programming RMID's and there is no conflict.


An example of this corrupting pqos monitoring:
1. Generate memory B/W with membw on core 2: `cd intel-cmt-cat/tools/membw && ./membw -c 2 -b 5000 --read`
2. Start RDT monitoring on core 2 using the OS interface (Resctrl): `pqos -I -m all:2`
```
    CORE         IPC      MISSES     LLC[KB]   MBL[MB/s]   MBR[MB/s]
       2        1.02      61083k     35784.0      4874.8         0.0
```
3. Start PCM in another terminal: `pcm-memory.x`
In pqos output, B/W reported will likely drop to 0MB/s:
```
    CORE         IPC      MISSES     LLC[KB]   MBL[MB/s]   MBR[MB/s]
       2        1.02      60613k         0.0         0.0         0.0
```
This is because is has been associated to a new RMID and the pqos utility (Rectrl) is still reading the old RMID counter.

Regards,
Marcel

**Comment by kmabbasi** [comment]
We haven't heard anything back from you. I am going to close this issue now by considering that it is resolved.

Thanks,
Khawar
