### ISSUE TITLE
CAT not working on Xeon Gold 6256

### ISSUE THREAD

**Issue by krunal1313** [intel/intel-cmt-cat#187]
Hi,
I'm using CAT on one of my machine with intel i7 6950xe processor and it is working as expected.

Now I'm trying to use same on my another box with intel xeon gold 6256 processor it is not working as expected.

following is the output from pqos -s -v,
INFO: L3 CAT details: CDP support=1, CDP on=0, #COS=16, #ways=11, ways contention bit-mask 0x600
INFO: L3 CAT details: cache size 34603008 bytes, way size 3145728 bytes

I'm setting COS masks as follow and assigning to cores,
    L3CA COS1 => MASK 0x1
    L3CA COS2 => MASK 0x6

    Core 1, L2ID 37, L3ID 1 => COS1, RMID0
    Core 3, L2ID 45, L3ID 1 => COS2, RMID0
    
Still, when I run the command pqos for monitoring LLC and misses, the LLC numbers on those cores keeps fluctuating and misses count is always more than 100k.

Differences between these two is with their architecture. i7 one is with broadwell and xeon is with cascade lake.
Moreover both are running on same OS - Ubuntu 18.04 LTS and kernel version are also same - 4.15.0-142-generic.

Could you please help me out to setup CAT on Xeon Gold 6256.

Thanks

**Comment by mdcornu** [comment]
The main architectural difference between these processors is  Cascade Lake supports a non-inclusive cache, meaning data loaded from memory will generally be brought into L2, bypassing LLC.  Because of this, the behavior of CAT on these systems may differ depending on the workload type.

Please also have a look here for more info on CAT behavior on 2nd Gen Xeon Processors:
https://software.intel.com/en-us/intel-resource-director-technology-rdt-reference-manual

**Comment by kmabbasi** [comment]
It's more than 3 weeks we haven't get any response.  I am going to close this for now.

Thanks,
Khawar
