### ISSUE TITLE
Installing problem

### ISSUE THREAD

**Issue by BojackFishman** [intel/intel-cmt-cat#258]
When I try to type "make" in the bash to compile the package, I always get some errors like:

`cc: error: unrecognized command line option ‘-fcf-protection=full’; did you mean ‘-fstack-protector-all’?
`

I have confirmed that my gcc version is 7.5.0 , and make version is 4.3.
what's the problem?

**Comment by rstorozh** [comment]
Hi Bojack,

The issue is that gcc 7.5.0 doesn't support '-fcf-protection' option:
https://gcc.gnu.org/onlinedocs/gcc-7.5.0/gcc/Option-Summary.html#Option-Summary

Actually gcc 9.x supports it:
https://gcc.gnu.org/onlinedocs/gcc-9.5.0/gcc/Option-Summary.html#Option-Summary

If you look at the GCC release dates you will see that in 2019 at least 2 gcc 9.x versions were released along with 7.5:
https://gcc.gnu.org/develop.html#timeline:~:text=GCC%207.5%20release%20(2019%2D11%2D14)

So, the compiler version looks really outdated.
I am wondering what OS do you use and if this compiler default to this OS? Is there any chance to upgrade your compiler version to a newer one?

**Comment by BojackFishman** [comment]
> Hi Bojack,
> 
> The issue is that gcc 7.5.0 doesn't support '-fcf-protection' option: https://gcc.gnu.org/onlinedocs/gcc-7.5.0/gcc/Option-Summary.html#Option-Summary
> 
> Actually gcc 9.x supports it: https://gcc.gnu.org/onlinedocs/gcc-9.5.0/gcc/Option-Summary.html#Option-Summary
> 
> If you look at the GCC release dates you will see that in 2019 at least 2 gcc 9.x versions were released along with 7.5: https://gcc.gnu.org/develop.html#timeline:~:text=GCC%207.5%20release%20(2019%2D11%2D14)
> 
> So, the compiler version looks really outdated. I am wondering what OS do you use and if this compiler default to this OS? Is there any chance to upgrade your compiler version to a newer one?

Thanks for your reply !
Actually my OS version is Ubuntun 18.04 LTS, and yes gcc 7.5 default to it. 
I was misled by some inaccurate information and didn't check it carefully that I think gcc 7.5 support that option, so I was quite confused.  I shall verify the information catiously in the future. Thanks again for your patient reply. 

And by the way , in fact from gcc 8.4 the option  '-fcf-protection'  has been supported and  I just have a try.
