### ISSUE TITLE
Thread-level Monitoring (2)

### ISSUE THREAD

**Issue by narru19** [intel/intel-cmt-cat#61]
Hi once again!

With reference to #57, I've updated to a kernel that allows me to use the per-thread monitoring capability (more specifically, 4.13). 

While using the API, (i.e. _**./monitor_app -I**_ also reports this) I get the following warning: 

> WARN: As of Kernel 4.10, Intel(R) RDT perf results per core are found to be incorrect.

Could I get any information as to what results are incorrect? Should I not take any measurements obtained with the API for granted? Also, does this mean per-thread results are incorrect as well?

Regards,

Toni

**Comment by mdcornu** [comment]
Hi Toni,

Right now, the Linux kernel does not support monitoring on a per core basis. The values returned are invalid, as mentioned in the warning above. This is will be fixed in future kernels.

However, monitoring on a per thread basis is functional.
Example: `./monitor_app -I -p <PID1> <PID2> <PID3> ...`

Regards,
Marcel
