### ISSUE TITLE
Kernel requirement for MBA

### ISSUE THREAD

**Issue by celeryfake** [intel/intel-cmt-cat#99]
Dear developers,

I am new to the intel-cmt-cat tool. I am working on a project that needs to throttle the DRAM bandwidth which this tool perfectly meets my needs. 
My platform is a Intel Xeon Gold 6152 CPU. The OS is Ubuntu 16.04 (4.4.0 kernel).
I tried the MBA utility it works fine for me. My question is according to the Wiki, MBA need 4.18+ kernel support. While in my test I use the stock 4.4.0 kernel. It also works. 
I guess this is working under the MSR interface? What's the difference if I use a newer kernel (OS interface)? (I hope this MBA tool can minimize the software overhead as much as possible).

Thanks and best regards,
Mian

**Comment by kmabbasi** [comment]
Hi Mian,

In relation to your question, MBA SW Controller (MBA Ctrl) support is available on kernal 4.18 and later. However, MBA OS interface support is available since 4.12 kernel. Please note there is a difference in MBA and MBA Ctrl. MBA provides indirect and approximate control over memory bandwidth available per-core. However, MBA SW Ctrl is used where precise control is needed. For that MBM feature provides input to SW controller which makes decisions about the MBA throttling level to apply.

Intel-cmt-cat by default uses 'pqos' for MSR interface unless explicitly specify 'pqos -I' for Restctrl interface. As you mentioned you have kernel 4.4 and it works. It looks like you use 'pqos'.

You can find the difference between MSR & OS interface on https://github.com/intel/intel-cmt-cat under "Interfaces section"

I hope this clarifies your concern.

Thanks,
Khawar

**Comment by kmabbasi** [comment]
Hi Mian,
In general, the difference between MSR and OS interface is that the MSR has no dependency on Linux kernel versions because it directly programs the HW registers (MSR).

More specifically about MBA, following are the differences:

1. MSR based MBA - specify % available BW per core
2. OS based MBA - specify % available BW per core / task
3. OS based MBA SW Ctrl - specify BW in MBps per core / task

If you would prefer not to upgrade your kernel,  you can use the rdtset tool which provides a simple MBA SW Ctrl that allows to specifiy BW in MBps (MSR interface only)

I hope this answers your question
Thanks,
Khawar

**Comment by celeryfake** [comment]
> Hi Mian,
> In general, the difference between MSR and OS interface is that the MSR has no dependency on Linux kernel versions because it directly programs the HW registers (MSR).
> 
> More specifically about MBA, following are the differences:
> 
> 1. MSR based MBA - specify % available BW per core
> 2. OS based MBA - specify % available BW per core / task
> 3. OS based MBA SW Ctrl - specify BW in MBps per core / task
> 
> If you would prefer not to upgrade your kernel, you can use the rdtset tool which provides a simple MBA SW Ctrl that allows to specifiy BW in MBps (MSR interface only)
> 
> I hope this answers your question
> Thanks,
> Khawar

Hi Khawar,

Thanks a lot for the detailed explaination. I've played with the OS interface with an updated kernel. Unfortunately, it doesn't support the mba_MBps mount option. I will try the rdtset tool you pinned me and see how it goes. By the way, please close this issue if needed.

Best regards,
Mian

**Comment by kmabbasi** [comment]
Thanks for your feedback.

Please feel free to open new issue if you are facing difficulties.

Regards,
Khawar
